// react/4-shoppingapp/frontend/src/components/ShoppingList.js
import React from 'react';
import {Table,Button} from 'semantic-ui-react';
import Row from './Row';
import RemoveRow from './RemoveRow';
import EditRow from './EditRow';

export default class ShoppingList extends React.Component {

	constructor(props) {
		super(props);
		this.state = {
			removeIndex:-1,
			editIndex:-1,
			search:""
		}
	}

	change = (event) => {
		let state = {};
		state[event.target.name] = event.target.value;
		this.setState(state);
	}

	searchByType = (event) => {
		this.props.getList(this.state.search);
		this.setState({
			search:""
		})
	}
	
	changeToRemoveMode = (id) => {
		for(let i=0;i<this.props.list.length;i++) {
			if(id === this.props.list[i]._id) {
				this.setState({
					removeIndex:i,
					editIndex:-1
				})
			}
		}
	}
	
	changeToEditMode = (id) => {
		for(let i=0;i<this.props.list.length;i++) {
			if(id === this.props.list[i]._id) {
				this.setState({
					removeIndex:-1,
					editIndex:i
				})
			}
		}
	}
	
	removeFromList = (id) => {
		this.props.removeFromList(id);
		this.cancel();
	}
	
	editItem = (item) => {
		this.props.editItem(item);
		this.cancel();
	}
	
	cancel = () => {
		this.setState({
			removeIndex:-1,
			editIndex:-1
		})
	}

	render() {
		let items = this.props.list.map((item,index) => {
			if(this.state.editIndex === index) {
				return <EditRow key={item._id} item={item}
					editItem={this.editItem} cancel={this.cancel}/>
			}
			if(this.state.removeIndex === index) {
				return <RemoveRow key={item._id} item={item}
						cancel={this.cancel}
						removeFromList={this.removeFromList}/>
			}
			return <Row key={item._id} item={item}
				changeToRemoveMode={this.changeToRemoveMode}
				changeToEditMode={this.changeToEditMode}/>
		
		})
		return(
		<div>
			<label htmlFor="search">Search by type:</label>
			<input type="text"
					name="search"
					onChange={this.change}
					value={this.state.search}/>
			<Button style={{marginLeft:10}} onClick={this.searchByType}>Search</Button>
			<Table celled>
				<Table.Header>
					<Table.Row>
						<Table.HeaderCell>Item Type</Table.HeaderCell>
						<Table.HeaderCell>Count</Table.HeaderCell>
						<Table.HeaderCell>Price</Table.HeaderCell>
						<Table.HeaderCell>Remove</Table.HeaderCell>
						<Table.HeaderCell>Edit</Table.HeaderCell>
					</Table.Row>
				</Table.Header>
				<Table.Body>
				{items}
				</Table.Body>
			</Table>
		</div>
		)
	}

}

// vue/shoppinglistvuex/src/views/ShoppingList.vue
<template>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Item type</th>
				<th>Count</th>
				<th>Price</th>
				<th>Remove</th>
				<th>Edit</th>
			</tr>
		</thead>
		<tbody>
			<tr v-for="item in $store.state.list" :key="item.id">
				<template v-if="editId != item.id">
					<td>{{item.type}}</td>
					<td>{{item.count}}</td>
					<td>{{item.price}}</td>
					<td><button class="btn btn-primary"
						v-on:click="remove(item.id)">Remove</button></td>
					<td><button class="btn btn-dark"
						v-on:click="edit(item.id)">Edit</button></td>
				</template>
				<template v-else>
					<td><input v-model="item.type"/></td>
					<td><input type="number" minimum="0" v-model="item.count"/></td>
					<td><input type="number" minimum="0" step="0.01" v-model="item.price"/></td>
					<td><button class="btn btn-success" v-on:click="saveItem()">Save</button></td>
					<td><button class="btn btn-danger" v-on:click="cancel()">Cancel</button></td>
				</template>
			</tr>
		</tbody>
	</table>
</template>
<script>
export default {
	name:"ShoppingList",
	data() {
		return {
			editId:-1,
			item: {
				id:0,
				type:"",
				price:0,
				count:0
			}
		}
	},
	methods: {
		remove:function(id) {
			this.$store.dispatch("removeFromList",id);
		},
		edit:function(id) {
			for(let i=0;i<this.$store.state.list.length;i++) {
				if(id == this.$store.state.list[i].id) {
					this.editId = id;
					this.item = this.$store.state.list[i];
					return;
				}
			}
		},
		saveItem:function() {
			this.$store.dispatch("editItem",this.item);
			this.cancel();
		},
		cancel:function() {
			this.item = {
				id:0,
				type:"",
				price:0,
				count:0
			}
			this.editId = -1;		
		}
	}
}
</script>
