// angular/routing/src/app/components/shoppingform.component.ts
import {Component} from '@angular/core'
import {ShoppingItem} from '../models/shoppingitem.model';
import {ShoppingService} from '../services/shoppingservice.service';

@Component({
	selector:"shoppingform",
	templateUrl:"./shoppingform.component.html"
})
export class ShoppingForm {
	
	shoppingitem:ShoppingItem = new ShoppingItem("",0,0,0);
	
	constructor(private _shopping:ShoppingService) {}

	addToList() {
		this._shopping.addToList(this.shoppingitem);
		this.shoppingitem = new ShoppingItem("",0,0,0);
	}
	
}
<form (ngSubmit)="addToList()" #shoppingForm="ngForm">
	<div class="form-group">
		<label for="type">Type:</label>
		<input type="text"
				name="type"
				[(ngModel)]="shoppingitem.type"/>
	</div>
	<div class="form-group">
		<label for="count">Count:</label>
		<input type="number"
				name="count"
				[(ngModel)]="shoppingitem.count"/>
	</div>
	<div class="form-group">
		<label for="price">Price:</label>
		<input type="number"
				name="price"
				[(ngModel)]="shoppingitem.price"/>
	</div>
	<input type="submit" class="btn btn-primary" value="Add"/>
</form>

// vue/shoppinglistvuex/src/views/ShoppingForm.vue
<template>
	<div>
		<div class="form form-group">
			<label for="type">Item type:</label>
			<input type="text"
					name="type"
					v-model="item.type"/>
		</div>
		<div class="form form-group">
			<label for="price">Price:</label>
			<input type="number"
					name="price"
					v-model="item.price"
					minimum="0"
					step="0.01"/>
		</div>
		<div class="form form-group">
			<label for="count">Count:</label>
			<input type="number"
					name="count"
					v-model="item.count"
					minimum="0"/>
		</div>
		<button v-on:click="addToList()"
				class="btn btn-primary">Add</button>
	</div>
</template>
<script>
export default {
	name:"ShoppingForm",
	data() {
		return {
			item: {
				id:0,
				type:"",
				price:0,
				count:0
			}
		}
	},
	methods: {
		addToList: function() {
			this.$store.dispatch("addToList",this.item);
			this.item = {
				id:0,
				type:"",
				price:0,
				count:0
			}
		}
	}
}
</script>
