// vue/shoppinglist/src/components/ShoppingList.vue
<template>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Item Type</th>
				<th>Count</th>
				<th>Price</th>
				<th>Remove</th>
			</tr>
		</thead>
		<tbody>
			<tr v-for="item in list" :key="item.id">
				<td>{{item.type}}</td>
				<td>{{item.count}}</td>
				<td>{{item.price}}</td>
				<td><button class="btn btn-secondary" 
				v-on:click="remove(item.id)">Remove</button></td>
			</tr>
		</tbody>
	</table>
</template>
<script>
export default {
	name:"ShoppingList",
	props:['list'],
	methods: {
		remove:function(id){
			this.$emit("remove-from-list",id);
		}
	}
}
</script>

// angular/routing/src/app/components/shoppinglist.component.ts
import {Component, OnInit} from '@angular/core';
import {ShoppingItem} from '../models/shoppingitem.model';
import {ShoppingService} from '../services/shoppingservice.service';

@Component({
	selector:"shoppinglist",
	templateUrl:"./shoppinglist.component.html"
})
export class ShoppingList implements OnInit {
	
	
	shoppinglist:ShoppingItem[] = []
	constructor(private _shopping:ShoppingService) {}

	ngOnInit() {
		this.getList();
	}
	
	getList() {
		this.shoppinglist = this._shopping.getList();
	}
	
	removeFromList(idx) {
		this._shopping.removeFromList(idx);
		this.getList();
	}
}
<div>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Type</th>
				<th>Count</th>
				<th>Price</th>
				<th>Remove</th>
			</tr>
		</thead>
		<tbody>
			<tr *ngFor="let item of shoppinglist;let idx=index">
				<td>{{item.type}}</td>
				<td>{{item.count}}</td>
				<td>{{item.price}}</td>
				<td><button class="btn btn-secondary"
					(click)="removeFromList(idx)">Remove</button></td>
			</tr>
		</tbody>
	</table>
</div>
