// vue/shoppinglistvuex/src/views/ShoppingForm.vue
<template>
	<div>
		<div class="form form-group">
			<label for="type">Item type:</label>
			<input type="text"
					name="type"
					v-model="item.type"/>
		</div>
		<div class="form form-group">
			<label for="price">Price:</label>
			<input type="number"
					name="price"
					v-model="item.price"
					minimum="0"
					step="0.01"/>
		</div>
		<div class="form form-group">
			<label for="count">Count:</label>
			<input type="number"
					name="count"
					v-model="item.count"
					minimum="0"/>
		</div>
		<button v-on:click="addToList()"
				class="btn btn-primary">Add</button>
	</div>
</template>
<script>
export default {
	name:"ShoppingForm",
	data() {
		return {
			item: {
				id:0,
				type:"",
				price:0,
				count:0
			}
		}
	},
	methods: {
		addToList: function() {
			this.$store.dispatch("addToList",this.item);
			this.item = {
				id:0,
				type:"",
				price:0,
				count:0
			}
		}
	}
}
</script>

// react/hooks-1-usestate/src/components/ShoppingForm.js
import React, {useState} from 'react';
import {Form,Button} from 'semantic-ui-react';

const ShoppingForm = ({addToList}) => {

	const [form,setValues] = useState({
		type:"",
		price:0,
		count:0
	})

	const onChange = (event) => {
		setValues({
			...form,
			[event.target.name]:event.target.value
		})
	}
	
	const onSubmit = (event) => {
		event.preventDefault();
		addToList(form);
	}
	
	return (
	<div style={{width:600,margin:"auto"}}>
		<Form onSubmit={onSubmit}>
			<Form.Field>
				<label htmlFor="type">Type</label>
				<input type="text"
						name="type"
						onChange={onChange}
						value={form.type}/>
			</Form.Field>
			<Form.Field>
				<label htmlFor="count">Count</label>
				<input type="number"
						name="count"
						min="0"
						onChange={onChange}
						value={form.count}/>
			</Form.Field>
			<Form.Field>
				<label htmlFor="price">Price</label>
				<input type="number"
						name="price"
						min="0"
						step="0.01"
						onChange={onChange}
						value={form.price}/>
			</Form.Field>
			<Button type="submit">Add</Button>
		</Form>
	</div>
	)
}

export default ShoppingForm
